const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

console.log('\x1b[34m%s\x1b[0m', '🚀 Kiri Store Project Initialization');
console.log('\x1b[34m%s\x1b[0m', '======================================');

/**
 * [1] Create local.properties if missing
 */
const localPropsPath = path.join(__dirname, 'local.properties');

if (!fs.existsSync(localPropsPath)) {
    console.log('\n[1] Creating local.properties...');
    const defaultContent = `# Kiri Store Local Properties
# Generated by ks-init.js on ${new Date().toISOString()}

# Get your Client ID from GitHub -> Settings -> Developer settings -> OAuth Apps
GITHUB_CLIENT_ID=YOUR_CLIENT_ID_HERE

# Paths to SDKs (optional, usually handled by IDE or environment)
# sdk.dir=C:\\Users\\yourname\\AppData\\Local\\Android\\Sdk
`;
    fs.writeFileSync(localPropsPath, defaultContent);
    console.log('✅ Created local.properties template.');
    console.log('🚩 ACTION REQUIRED: Open local.properties and set your GITHUB_CLIENT_ID.');
} else {
    console.log('\n[1] local.properties already exists. Skipping...');
}

/**
 * [2] Check JDK version
 */
console.log('\n[2] Checking JDK version...');
try {
    const javaVersion = execSync('java -version', { stdio: 'pipe' }).toString();
    console.log('✅ Java is installed.');
} catch (e) {
    // java -version often outputs to stderr
    const stderr = e.stderr ? e.stderr.toString() : '';
    if (stderr.includes('version')) {
        console.log('✅ Java is installed.');
    } else {
        console.log('\x1b[31m%s\x1b[0m', '❌ Java NOT found. Please install JDK 21+.');
    }
}

/**
 * [3] Next Steps
 */
console.log('\n\x1b[32m%s\x1b[0m', '✨ Initialization complete!');
console.log('👉 To run on Desktop: ./gradlew :composeApp:run');
console.log('👉 To run on Android: ./gradlew :composeApp:assembleDebug');
console.log('👉 For help: node ks-doctor.js');

